Repository systers/powerup-android, pull requests merged in 2018-05, with the labels that each got.

#1140 Created main screen for PreGame Setup
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor4.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor5.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor6.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor7.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor8.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor9.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_4.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_5.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_6.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_7.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_8.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/doctor_9.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/friend1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/friend2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/friend3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/friend_1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/friend_2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/friend_3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister5.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister6.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister_1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister_2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister_3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister_4.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister_5.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister_6.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/teacher1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/teacher2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/teacher3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/teacher_1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/teacher_2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/teacher_3.webp
  PowerUp/app/src/main/res/layout-land/activity_pregame_setup.xml
  PowerUp/app/src/main/res/layout/pregame_setup_list_item.xml
  PowerUp/app/src/main/res/values-land/dimens.xml
  PowerUp/app/src/main/res/values/strings.xml
Labels: Program: GSoC

#856 Program GCI: Refactoring ScenarioOverActivity class
  PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java
Labels: Program: GCI

#1131 Including dummy data for all 4 scenarios
  PowerUp/app/src/main/assets/Answer.csv
  PowerUp/app/src/main/assets/Question.csv
  PowerUp/app/src/main/assets/Scenario.csv
Labels: Program: GSoC

#1142 Modify game activity
  PowerUp/app/src/main/res/layout-land/game_activity.xml
Labels: Category: User Interface, Program: GSoC, Type: Enhancement
