Repository systers/powerup-android, pull requests merged in 2018-06, with the labels that each got.

#665 LeakCanary Added to detect Memory Leaks
  PowerUp/app/build.gradle
  PowerUp/app/src/main/AndroidManifest.xml
  PowerUp/app/src/main/java/powerup/systers/com/LeakCheckApplication.java
Labels: Program: GCI

#1151 Save chosen options
  PowerUp/app/src/main/java/powerup/systers/com/datamodel/SessionHistory.java
  PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
  PowerUp/app/src/main/java/powerup/systers/com/pregame_setup/PregameSetupActivity.java
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister2.png
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister3.png
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister4.png
  PowerUp/app/src/main/res/drawable-xxxhdpi/sister4.webp
  PowerUp/build.gradle
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#1153 Update game activity to include proper NPCs
  PowerUp/app/build.gradle
  PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java
  PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
  PowerUp/app/src/main/java/powerup/systers/com/pregame_setup/PreGameSetupInitialActivity.java
  PowerUp/app/src/main/java/powerup/systers/com/pregame_setup/PregameSetupActivity.java
  PowerUp/build.gradle
Labels: Category: Coding, Category: User Interface, Program: GSoC, Type: Enhancement

#1176 Added layout for main screen of mini game 1
  PowerUp/app/src/main/res/drawable-xxxhdpi/btn_done.png
  PowerUp/app/src/main/res/drawable-xxxhdpi/btn_done.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/ic_keyboard_arrow_right_white_18dp.png
  PowerUp/app/src/main/res/drawable-xxxhdpi/ic_keyboard_arrow_right_white_18dp.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/img_pregame.png
  PowerUp/app/src/main/res/drawable-xxxhdpi/img_pregame.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/none.png
  PowerUp/app/src/main/res/drawable-xxxhdpi/none.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/virus_1.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/virus_2.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/virus_3.webp
  PowerUp/app/src/main/res/drawable-xxxhdpi/virus_4.webp
  PowerUp/app/src/main/res/drawable/arrow_kill.xml
  PowerUp/app/src/main/res/layout-land/activity_kill_the_virus_game.xml
  PowerUp/app/src/main/res/values/dimens.xml
  PowerUp/app/src/main/res/values/strings.xml
  PowerUp/build.gradle
Labels: Category: User Interface, Program: GSoC, Type: Enhancement

#1174 Adding tests for PreGameSetupActivity
  PowerUp/app/src/main/java/powerup/systers/com/pregame_setup/PregameSetupActivity.java
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/PregameSetupActivityTest.java
Labels: Category: Coding, Category: Quality Assurance, Program: GSoC

#1173 Added tests for initial activity of PreGame setup
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/PreGameSetupInitialActivityTest.java
Labels: Category: Quality Assurance, Program: GSoC

#1178 Add game end screen for kill the virus
  PowerUp/app/src/main/res/drawable-xxxhdpi/kill_virus_end.webp
  PowerUp/app/src/main/res/layout-land/activity_kill_the_virus_end.xml
  PowerUp/app/src/main/res/values/dimens.xml
Labels: Category: User Interface, Program: GSoC, Type: Enhancement

#1190 Added layout for main screen of memory match
  PowerUp/app/src/main/res/layout-land/activity_memory_match_game.xml
  PowerUp/app/src/main/res/values-land/dimens.xml
  PowerUp/app/src/main/res/values/dimens.xml
  PowerUp/app/src/main/res/values/strings.xml
Labels: Category: User Interface, Program: GSoC, Type: Enhancement

#1192 Added end screen for memory match
  PowerUp/app/src/main/res/layout-land/activity_memory_match_end.xml
  PowerUp/app/src/main/res/values/dimens.xml
Labels: Category: User Interface, Program: GSoC

#1200 Add tutorials for kill the virus
  PowerUp/app/src/main/res/drawable/btn_bg.xml
  PowerUp/app/src/main/res/layout-land/activity_kill_the_virus_tutorial.xml
  PowerUp/app/src/main/res/values/dimens.xml
  PowerUp/app/src/main/res/values/strings.xml
Labels: Category: Coding, Category: User Interface, Program: GSoC

#1184 Adding JUnit tests for tutorial screens
  PowerUp/app/src/main/AndroidManifest.xml
  PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusTutorials.java
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/KillTheVirusTutorialTest.java
Labels: Category: Quality Assurance, Program: GSoC

#1191 Added tutorial screens for Memory Match game
  PowerUp/app/src/main/res/layout-land/activity_memory_match_tutorial.xml
  PowerUp/app/src/main/res/values/dimens.xml
  PowerUp/app/src/main/res/values/strings.xml
Labels: Category: Coding, Category: User Interface

#1204 Added functionality to main screen of mini game 1
  PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java
  PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
  PowerUp/app/src/main/res/animator/translate.xml
  PowerUp/app/src/main/res/drawable/arrow_kill.xml
  PowerUp/app/src/main/res/values/array.xml
  PowerUp/app/src/main/res/values/strings.xml
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/KillTheVirusGameTest.java
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#1206 Kill the virus tutorials
  PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusTutorials.java
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#1196 Added JUnit tests for main screen of memory match"
  PowerUp/app/src/main/AndroidManifest.xml
  PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java
  PowerUp/app/src/main/res/layout-land/activity_memory_match_game.xml
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchGameTest.java
Labels: Category: Coding, Category: Quality Assurance, Program: GSoC

#1197 Added JUnit tests for tutorial screen of Memory Match
  PowerUp/app/src/main/AndroidManifest.xml
  PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchTutorialActivity.java
  PowerUp/app/src/main/res/layout-land/activity_memory_match_tutorial.xml
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchTutorialTest.java
Labels: Category: Quality Assurance, Program: GSoC

#1208 Added functionality to end screen
  PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusEndActivity.java
  PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java
  PowerUp/app/src/main/res/layout-land/activity_kill_the_virus_end.xml
Labels: Category: Coding, Program: GSoC

#1198 Added JUnit tests for end screen of mini game 2
  PowerUp/app/src/main/AndroidManifest.xml
  PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchEndActivity.java
  PowerUp/app/src/main/res/layout-land/activity_memory_match_end.xml
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchEndTest.java
Labels: Category: Coding, Category: Quality Assurance, Program: GSoC

#1209 Added tests for main screen of mini game 1
  PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java
  PowerUp/app/src/test/java/powerup/systers/com/powerup/test/KillTheVirusGameTest.java
Labels: Category: Quality Assurance, Program: GSoC
